import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import Footer from "@/components/Footer";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Brain Games 2024",
    description: "Generated by create next app",
    metadataBase: new URL('https://braingames.icssc.club'),
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={inter.className}
                style={{
                    backgroundImage: 'url("background.svg")',
                    backgroundSize: "cover",
                    backgroundRepeat: "no-repeat", 
                }}
            >
                <div className="lightnings">
                    <img className="lightning" src="lightning.svg" />
                    <img className="lightning" src="lightning.svg" />
                    <img className="lightning" src="lightning.svg" />
                    <img className="lightning" src="lightning.svg" />
                    <img className="lightning" src="lightning.svg" />
                    <img className="lightning" src="lightning.svg" />
                    <img className="lightning" src="lightning.svg" />
                    <img className="lightning" src="lightning.svg" />
                    <img className="lightning" src="lightning.svg" />
                </div>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
